### PR TITLE
Use heroku-node

### PR DESCRIPTION
**Pull request by apechimp**
This uses heroku node so that in heroku, we'll use saner memory settings.

### CODE REVIEW

**Comment by apechimp** [comment]
CR @lanetix/engineers

**Comment by tone81** [comment]
The changes look :checkered_flag: , but Travis is blowing up.

**Comment by apechimp** [comment]
Yeah, @DannyDouglass @scarney81 @troygoode @OronNadiv can one of you disable travis for this repo? We're using circle instead now.

**Comment by scarney81** [comment]
Done @apechimp

**Pull request merged**
