### PR TITLE
Misc fixup

### PR DESCRIPTION
**Pull request by apechimp**
* Vim swap files (*boo* *hiss* I know)
* npm scripts over broken bin scripts :stuck_out_tongue: 
* Continuation of my IIFE crusade

### CODE REVIEW

**Comment by apechimp** [comment]
CR @lanetix/engineers 

Also, I can't push to this repo hence the fork.

**Comment by tone81** [comment]
Maybe not for this PR, but it makes sense to create a template README.md file with some basic headers so people can fill out the details about the microservice once it's generated.

If that's a future PR, then :bow:.

**Comment by apechimp** [comment]
#3 created for ^^

**Comment by scarney81** [comment]
Good suggestion @tone81

**Comment by scarney81** [comment]
:ship:

**Comment by troygoode** [comment]
I really like @tone81's suggestion above.

**Pull request merged**
