### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by apolishch**

### CODE REVIEW

**Comment by scarney81** [comment]
:shower:

**Comment by apechimp** [comment]
@apolishch this was using travis for ci since it's public, can you adapt your solution to use that, or at least make it so it doesn't use both :wink:

**Comment by apolishch** [comment]
@apechimp This has no effect on travis/running on circle. This is in the templates directory

**Comment by apechimp** [comment]
Ahh, so this has actually been a problem we've had for a while then. Merge away!

**Comment by scarney81** [comment]
Looks like I originally put this on circle and it's been partially moved to travis

**Comment by apechimp** [comment]
@scarney81 we should just get it all on circle. Travis is very slow and now won't check code coverage.

**Comment by scarney81** [comment]
No disagreement. Circle supports all the same stuff and more. So... yeah

**Pull request merged**
